exports.productsData = [
  {
    "id": 1,
    "liked": false,
    "inCart": false,
    "author": "Coldplay",
    "name": "Parachutes",
    "year": 2000,
    "style": "Alternative Rock, Post-Britpop",
    "country": "United Kingdom",
    "albumCoverName": "coldplay-parachutes",
  },
  {
    "id": 2,
    "liked": false,
    "inCart": false,
    "author": "Coldplay",
    "name": "A Rush Of Blood To The Head",
    "year": 2002,
    "style": "Pop Rock, Alternative Rock",
    "country": "United Kingdom",
    "albumCoverName": "coldplay-rush",
  },
  {
    "id": 3,
    "liked": false,
    "inCart": false,
    "author": "Coldplay",
    "name": "X&Y",
    "year": 2005,
    "style": "Pop Rock, Electronic",
    "country": "United Kingdom",
    "albumCoverName": "coldplay-xy",
  },
  {
    "id": 4,
    "liked": false,
    "inCart": false,
    "author": "Coldplay",
    "name": "Viva la Vida or Death and All His Friends",
    "year": 2008,
    "style": "Alternative Rock, Baroque Pop",
    "country": "United Kingdom",
    "albumCoverName": "coldplay-viva",
  },
  {
    "id": 5,
    "liked": false,
    "inCart": false,
    "author": "Coldplay",
    "name": "Mylo Xyloto",
    "year": 2011,
    "style": "Pop, Electronic",
    "country": "United Kingdom",
    "albumCoverName": "coldplay-mylo",
  },
  {
    "id": 6,
    "liked": false,
    "inCart": false,
    "author": "Coldplay",
    "name": "Ghost Stories",
    "year": 2014,
    "style": "Electronic, Synth-Pop",
    "country": "United Kingdom",
    "albumCoverName": "coldplay-ghost-stories",
  },
  {
    "id": 7,
    "liked": false,
    "inCart": false,
    "author": "Coldplay",
    "name": "A Head Full of Dreams",
    "year": 2015,
    "style": "Pop, Electronic",
    "country": "United Kingdom",
    "albumCoverName": "coldplay-head-full",
  },
  {
    "id": 8,
    "liked": false,
    "inCart": false,
    "author": "Coldplay",
    "name": "Everyday Life",
    "year": 2019,
    "style": "Alternative, Gospel, World",
    "country": "United Kingdom",
    "albumCoverName": "coldplay-everyday",
  },
  {
    "id": 9,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "The Red Hot Chili Peppers",
    "year": 1984,
    "style": "Funk Rock, Punk Rock",
    "country": "United States",
    "albumCoverName": "rhcp-the-rhcp",
  },
  {
    "id": 10,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "Freaky Styley",
    "year": 1985,
    "style": "Funk Rock",
    "country": "United States",
    "albumCoverName": "rhcp-freaky",
  },
  {
    "id": 11,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "The Uplift Mofo Party Plan",
    "year": 1987,
    "style": "Funk Rock, Punk Rock",
    "country": "United States",
    "albumCoverName": "rhcp-uplift",
  },
  {
    "id": 12,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "Mother's Milk",
    "year": 1989,
    "style": "Funk Metal, Rock",
    "country": "United States",
    "albumCoverName": "rhcp-mothers-milk",
  },
  {
    "id": 13,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "Blood Sugar Sex Magik",
    "year": 1991,
    "style": "Funk Rock, Alternative Rock",
    "country": "United States",
    "albumCoverName": "rhcp-blood-sugar",
  },
  {
    "id": 14,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "One Hot Minute",
    "year": 1995,
    "style": "Alternative Rock, Funk Metal",
    "country": "United States",
    "albumCoverName": "rhcp-one-hot-minute",
  },
  {
    "id": 15,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "Californication",
    "year": 1999,
    "style": "Alternative Rock, Funk Rock",
    "country": "United States",
    "albumCoverName": "rhcp-californication",
  },
  {
    "id": 16,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "By the Way",
    "year": 2002,
    "style": "Alternative Rock, Pop Rock",
    "country": "United States",
    "albumCoverName": "rhcp-by-the-way",
  },
  {
    "id": 17,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "Stadium Arcadium",
    "year": 2006,
    "style": "Alternative Rock, Funk Rock",
    "country": "United States",
    "albumCoverName": "rhcp-stadium-arcadium",
  },
  {
    "id": 18,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "I'm with You",
    "year": 2011,
    "style": "Alternative Rock, Funk Rock",
    "country": "United States",
    "albumCoverName": "rhcp-im-with-you",
  },
  {
    "id": 19,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "The Getaway",
    "year": 2016,
    "style": "Alternative Rock, Pop Rock",
    "country": "United States",
    "albumCoverName": "rhcp-the-getaway",
  },
  {
    "id": 19,
    "liked": false,
    "inCart": false,
    "author": "Red Hot Chili Peppers",
    "name": "Unlimited Love",
    "year": 2022,
    "style": "Alternative Rock, Funk",
    "country": "United States",
    "albumCoverName": "rhcp-unlimited-love",
  },
  {
    "id": 20,
    "liked": false,
    "inCart": false,
    "author": "Bad Omens",
    "name": "Bad Omens",
    "year": 2016,
    "style": "Metalcore, Post-Hardcore",
    "country": "United States",
    "albumCoverName": "bad-omens",
  },
  {
    "id": 21,
    "liked": false,
    "inCart": false,
    "author": "Bad Omens",
    "name": "Finding God Before God Finds Me",
    "year": 2019,
    "style": "Metalcore, Post-Hardcore",
    "country": "United States",
    "albumCoverName": "bad-omens-finding",
  },
  {
    "id": 22,
    "liked": false,
    "inCart": false,
    "author": "Bad Omens",
    "name": "The Death of Peace of Mind",
    "year": 2021,
    "style": "Metalcore, Post-Hardcore",
    "country": "United States",
    "albumCoverName": "bad-omens-the-death",
  },
  {
    "id": 23,
    "liked": false,
    "inCart": false,
    "author": "Twenty One Pilots",
    "name": "Twenty One Pilots",
    "year": 2009,
    "style": "Indie Pop, Electropop",
    "country": "United States",
    "albumCoverName": "21-pilots",
  },
  {
    "id": 24,
    "liked": false,
    "inCart": false,
    "author": "Twenty One Pilots",
    "name": "Regional at Best",
    "year": 2011,
    "style": "Indie Pop, Electropop",
    "country": "United States",
    "albumCoverName": "21-pilots-regional",
  },
  {
    "id": 25,
    "liked": false,
    "inCart": false,
    "author": "Twenty One Pilots",
    "name": "Vessel",
    "year": 2013,
    "style": "Indie Pop, Electropop",
    "country": "United States",
    "albumCoverName": "21-pilots-vessel",
  },
  {
    "id": 26,
    "liked": false,
    "inCart": false,
    "author": "Twenty One Pilots",
    "name": "Blurryface",
    "year": 2015,
    "style": "Indie Pop, Electropop, Hip-Hop",
    "country": "United States",
    "albumCoverName": "21-pilots-blurryface",
  },
  {
    "id": 27,
    "liked": false,
    "inCart": false,
    "author": "Twenty One Pilots",
    "name": "Trench",
    "year": 2018,
    "style": "Indie Pop, Electropop, Hip-Hop",
    "country": "United States",
    "albumCoverName": "21-pilots-trench",
  },
  {
    "id": 28,
    "liked": false,
    "inCart": false,
    "author": "Twenty One Pilots",
    "name": "Scaled and Icy",
    "year": 2021,
    "style": "Indie Pop, Electropop, Synth-Pop",
    "country": "United States",
    "albumCoverName": "21-pilots-scaled",
  },
  {
    "id": 29,
    "liked": false,
    "inCart": false,
    "author": "Mother Mother",
    "name": "Touch Up",
    "year": 2007,
    "style": "Indie Rock, Pop Rock",
    "country": "Canada",
    "albumCoverName": "mother-touch",
  },
  {
    "id": 30,
    "liked": false,
    "inCart": false,
    "author": "Mother Mother",
    "name": "O My Heart",
    "year": 2008,
    "style": "Indie Rock, Pop Rock",
    "country": "Canada",
    "albumCoverName": "mother-o-my-heart",
  },
  {
    "id": 31,
    "liked": false,
    "inCart": false,
    "author": "Mother Mother",
    "name": "Eureka",
    "year": 2011,
    "style": "Indie Rock, Pop Rock",
    "country": "Canada",
    "albumCoverName": "mother-eureka",
  },
  {
    "id": 32,
    "liked": false,
    "inCart": false,
    "author": "Mother Mother",
    "name": "The Sticks",
    "year": 2012,
    "style": "Indie Rock, Pop Rock",
    "country": "Canada",
    "albumCoverName": "mother-the-sticks",
  },
  {
    "id": 33,
    "liked": false,
    "inCart": false,
    "author": "Mother Mother",
    "name": "Very Good Bad Thing",
    "year": 2014,
    "style": "Indie Rock, Pop Rock",
    "country": "Canada",
    "albumCoverName": "mother-good-bad",
  },
  {
    "id": 34,
    "liked": false,
    "inCart": false,
    "author": "Mother Mother",
    "name": "No Culture",
    "year": 2017,
    "style": "Indie Pop, Synth-Pop",
    "country": "Canada",
    "albumCoverName": "mother-no-culture",
  },
  {
    "id": 35,
    "liked": false,
    "inCart": false,
    "author": "Mother Mother",
    "name": "Inside",
    "year": 2021,
    "style": "Indie Pop, Synth-Pop",
    "country": "Canada",
    "albumCoverName": "mother-inside",
  }
]

